name: Build and Deploy Develop
on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@develop
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@develop
        with:
          name: build
          path: build
  deploy:
    name: Deploy Dev
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@develop
      - name: Download Artifact
        uses: actions/download-artifact@develop
        with:
          name: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@develop
        with:
          args: use covidonadev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy Develop to Firebase
        uses: w9jds/firebase-action@develop
        with:
          args: deploy --only hosting:covidonadev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}