name: Build and Deploy Production
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
  deploy:
    name: Deploy Prod
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
      - name: Deploy Prod to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: use covidonaProd
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy Prod to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:covidona-mx
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
